
services:
  flask-app:
    build: .
    ports:
      - "8001:8000"  # Changed host port to 8001
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb+srv://neel11:Neelpavi1234@cluster0.yxm11.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"  # Changed host port to 27018
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: