
services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8001:8000"
    volumes:
      - ./certs:/app/certs
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: